stages:
  tiler:
    cmd: C:\Develop\Python\Python37\python.exe ..\..\tools\Tiler\tiler.py
    wdir: Standalone_GCBM/layers/tiled
    deps:
    - ..\..\tools\Tiler\tiler.py
    - ..\raw\environment
    - ..\raw\inventory
  recliner2gcbm_x64:
    cmd: tools\Recliner2GCBM-x64\Recliner2GCBM.exe -c input_database\recliner2gcbm_config.json
    wdir: Standalone_GCBM
    deps:
    - input_database\gcbm_input.db
    - tools\recliner2gcbm-x64\recliner2gcbm.exe
  add_species_vol_to_bio:
    cmd: C:\Develop\Python\Python37\python.exe input_database\add_species_vol_to_bio.py
      input_database\gcbm_input.db
    wdir: Standalone_GCBM
    deps:
    - input_database\add_species_vol_to_bio.py
    - input_database\gcbm_input.db
  modify_root_parameters:
    cmd: C:\Develop\Python\Python37\python.exe input_database\modify_root_parameters.py
      input_database\gcbm_input.db
    wdir: Standalone_GCBM
    deps:
    - input_database\gcbm_input.db
    - input_database\modify_root_parameters.py
  modify_decay_parameters:
    cmd: C:\Develop\Python\Python37\python.exe input_database\modify_turnover_parameters.py
      input_database\gcbm_input.db
    wdir: Standalone_GCBM
    deps:
    - input_database\gcbm_input.db
    - input_database\modify_decay_parameters.py
  modify_turnover_parameters:
    cmd: C:\Develop\Python\Python37\python.exe input_database\modify_turnover_parameters.py
      input_database\gcbm_input.db
    wdir: Standalone_GCBM
    deps:
    - input_database\gcbm_input.db
    - input_database\modify_turnover_parameters.py
  modify_spinup_parameters:
    cmd: C:\Develop\Python\Python37\python.exe input_database\modify_spinup_parameters.py
      input_database\gcbm_input.db
    wdir: Standalone_GCBM
    deps:
    - input_database\gcbm_input.db
    - input_database\modify_spinup_parameters.py
